import type { Metadata } from 'next'
import Footer from './ui/footer';
import Header from './ui/header';
import { inter, lusitana, roboto } from '@/app/ui/fonts';

import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={roboto.className}>
      <Header />
      <main>{children}
      </main>
      <Footer />
      </body>
    </html>
  )
}
