import type { Metadata } from 'next'
import Footer from './ui/footer';
import Header from './ui/header';
import { inter, lusitana, roboto } from '@/app/ui/fonts';
import logo from '@/app/icon.jpg'

import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link
  rel="icon"
  href="/icon.png"
  type="image/png"
  sizes="32x32"
/>
      </head>
    
      
      <body className={roboto.className}>
      <Header />
      <main>{children}
      </main>
      <Footer />
      </body>
    </html>
  )
}
